/***********************************************************************/
/*                                                                     */
/*  FILE        :moyashi.c                                             */
/*  DATE        :Fri, Jan 07, 2022                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3694F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
#include "iodefine.h"
#include "led.h"
void main(void);
void InitSWScan(void);
unsigned char isSW1_ON(void);
unsigned char isSW2_ON(void);


void main(void)
{
	InitLED();

	while (1) {
		if (isSW1_ON()) {
			LED1_ON();
		} else {
			LED1_OFF();
		}

		if (isSW2_ON()) {
			LED2_ON();
		} else {
			LED2_OFF();
		}
	}
}

void InitSWScan(void)
{
	IO.PMR1.BIT.IRQ2 = 0;     // 汎用入出力としてP16を使う。
	IO.PMR1.BIT.IRQ3 = 0;     // 汎用入出力としてP17を使う。
}

unsigned char isSW1_ON(void)
{
	unsigned char ret;
	
	if (IO.PDR1.BIT.B6 == 1) {
		ret = 1;
	} else {
		ret = 0;
	}
	return ret;
}

unsigned char isSW2_ON(void)
{
	unsigned char ret;
	
	if (IO.PDR1.BIT.B7 == 1) {
		ret = 1;
	} else {
		ret = 0;
	}
	return ret;
}

